WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
WINDOW_TITLE = "Echoes Below"

FPS = 60
MAX_DELTA_TIME = 0.1
SPLASH_DURATION = 2.5
FLOOR_TRANSITION_DURATION = 1.6

COLOR_BACKGROUND = (8, 11, 18)
COLOR_BACKGROUND_ALT = (12, 18, 28)
COLOR_PANEL = (18, 28, 40)
COLOR_PANEL_HOVER = (29, 47, 61)
COLOR_PANEL_SELECTED = (33, 73, 88)
COLOR_TEXT = (221, 235, 232)
COLOR_TEXT_MUTED = (143, 166, 170)
COLOR_ACCENT = (89, 221, 211)
COLOR_ACCENT_DIM = (30, 120, 124)
COLOR_WARNING = (255, 96, 96)
COLOR_SUCCESS = (118, 241, 173)
COLOR_OVERLAY = (0, 0, 0, 170)

FONT_TITLE_SIZE = 78
FONT_SUBTITLE_SIZE = 34
FONT_BODY_SIZE = 26
FONT_SMALL_SIZE = 20
FONT_BUTTON_SIZE = 28

BUTTON_WIDTH = 330
BUTTON_HEIGHT = 56

TILE_SIZE = 48
PLAYER_SPEED = 180.0
PLAYER_COLLISION_WIDTH = 24
PLAYER_COLLISION_HEIGHT = 24
PLAYER_COLLISION_BOTTOM_OFFSET = 8
MOVEMENT_SUBSTEP_MAX = 12.0
MOVEMENT_MAX_SUBSTEPS = 32
LOCAL_VISIBILITY_RADIUS = 76

DOOR_OPEN_FRAME_DURATION = 0.09
DOOR_CLOSE_DELAY = 0.75
DOOR_APPROACH_TILES = 2
DOOR_COLLISION_THICKNESS = 12

# Static scan and echo rendering.
SCAN_RAY_COUNT = 720
SCAN_MAX_RADIUS = 900.0
SCAN_WAVE_SPEED = 850.0
SCAN_COOLDOWN = 1.3
STATIC_TRACE_LIFETIME = 3.8
SCAN_POINT_RADIUS = 2
SCAN_LINE_MAX_GAP = 18.0
SCAN_LINE_MAX_DISTANCE_DELTA = 24.0
SCAN_TRACE_DEDUPE_QUANTUM = 2.5
# Scan-detectable object snapshots and pickups.
OBJECT_SNAPSHOT_LIFETIME = 2.4
CREATURE_SNAPSHOT_LIFETIME = 1.5

# Phase 9 creature patrol and collision
CREATURE_SPEED = 115.0
CREATURE_COLLISION_SIZE = 38
CREATURE_MIN_PATROL_PATH_TILES = 4
CREATURE_PATROL_TARGET_ATTEMPTS = 18
CREATURE_WAYPOINT_REACHED_DISTANCE = 5.0
CREATURE_STUCK_REPATH_TIME = 0.45
CREATURE_REPATH_COOLDOWN = 0.18

# Phase 10 threat-aware creature AI
THREAT_EVENT_MAX_ACTIVE = 32
THREAT_PLAYER_SCAN_STRENGTH = 1.0
THREAT_PLAYER_SCAN_LIFETIME = 5.0
THREAT_DEFAULT_LIFETIME = 4.0
CREATURE_HEARING_RADIUS = TILE_SIZE * 15.0
CREATURE_THREAT_MIN_RELEVANCE = 0.02
CREATURE_THREAT_SWITCH_HYSTERESIS = 0.18
CREATURE_THREAT_EVALUATION_INTERVAL = 0.18
CREATURE_PATROL_REPATH_INTERVAL = 0.45
CREATURE_INVESTIGATE_REPATH_INTERVAL = 0.35
CREATURE_SEARCH_REPATH_INTERVAL = 0.4
CREATURE_CHASE_REPATH_INTERVAL = 0.22
CREATURE_PERCEPTION_INTERVAL = 0.1
CREATURE_DETECTION_DISTANCE = TILE_SIZE * 7.0
CREATURE_CHASE_SPEED = 150.0
CREATURE_SEARCH_DURATION = 4.5
CREATURE_SEARCH_RADIUS_TILES = 4
CREATURE_LOST_SIGHT_TIMEOUT = 1.7
MATERIAL_COLLISION_SIZE = 28
MATERIAL_CONTACT_HINT_RADIUS = 42.0
MATERIAL_PICKUP_SCORE = 5

# Phase 11 Floor 1 objective tuning.
GENERATOR_COMPONENT_COLLISION_SIZE = 30
GENERATOR_COMPONENT_SCORE = 50
GENERATOR_REPAIR_SCORE = 150
FLOOR_COMPLETION_SCORE = 300
GENERATOR_REPAIR_DURATION = 1.5
GENERATOR_INTERACTION_RADIUS_TILES = 1.5
GENERATOR_THREAT_STRENGTH = 2.6
GENERATOR_THREAT_LIFETIME = 9.0
OBJECTIVE_CONTACT_HINT_RADIUS = 52.0
CONTEXT_MESSAGE_DURATION = 2.2

